export type SourceCategory =
  | "UN_AGENCIES_POOLED_FUNDS"
  | "BILATERAL_DONORS"
  | "INGO_SUBGRANTS"
  | "PRIVATE_FOUNDATIONS"
  | "DEVELOPMENT_BANKS_MULTILATERAL"
  | "AGGREGATORS_DATABASES";

export type GrantSource = {
  category: SourceCategory;
  name: string;
  queryHints?: string[];
};

// IMPORTANT: This list is intended to be exhaustive per INARA requirements.
export const GRANT_SOURCES: GrantSource[] = [
  // UN AGENCIES & POOLED FUNDS
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "UN OCHA FTS (Financial Tracking Service)", queryHints: ["call for proposals", "grant", "NGO", "funding"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "Syria Humanitarian Fund (SHF)", queryHints: ["SHF", "call for proposals", "allocations"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "Afghanistan Humanitarian Fund (AHF)", queryHints: ["AHF", "call for proposals", "allocations"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "Lebanon Humanitarian Fund (LHF)", queryHints: ["LHF", "call for proposals", "allocations"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "Ukraine Humanitarian Fund (UHF)", queryHints: ["UHF", "call for proposals", "allocations"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "oPt Humanitarian Fund (Gaza/Palestine)", queryHints: ["oPt HF", "call for proposals", "Gaza"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "Egypt Humanitarian Fund", queryHints: ["call for proposals", "Egypt", "humanitarian fund"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "UNICEF partnership and grant portals", queryHints: ["UNICEF partnership", "funding opportunity", "grant"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "UNHCR innovation and partnership fund", queryHints: ["UNHCR innovation fund", "partnership", "call for proposals"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "UNDP partnership portals", queryHints: ["UNDP funding opportunity", "call for proposals", "partner with UNDP"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "WHO emergency and health grants", queryHints: ["WHO call for proposals", "health grant", "emergency"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "WFP partnership opportunities", queryHints: ["WFP partnership", "tender", "call for proposals"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "UNFPA humanitarian windows", queryHints: ["UNFPA call for proposals", "humanitarian", "funding"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "UN Women humanitarian and recovery grants", queryHints: ["UN Women call for proposals", "grant", "recovery"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "UNOCHA Rapid Response Fund", queryHints: ["rapid response fund", "OCHA", "allocations"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "UN Peacebuilding Fund", queryHints: ["Peacebuilding Fund", "call for proposals", "CSO"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "UNOPS vendor and grant portal", queryHints: ["UNOPS call for proposals", "UNOPS grant", "partnership"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "IOM Development Fund", queryHints: ["IOM Development Fund", "call for proposals", "NGO"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "UNRWA partnership opportunities (Gaza/Palestine specific)", queryHints: ["UNRWA partnership", "Gaza", "call for proposals"] },
  { category: "UN_AGENCIES_POOLED_FUNDS", name: "FAO emergency and resilience grants", queryHints: ["FAO call for proposals", "emergency", "resilience"] },

  // MAJOR BILATERAL DONORS
  { category: "BILATERAL_DONORS", name: "USAID (Bureau for Humanitarian Assistance — BHA; Bureau for Development; Democracy and Governance)", queryHints: ["USAID BHA funding opportunity", "APS", "RFA", "NOFO"] },
  { category: "BILATERAL_DONORS", name: "FCDO (UK Foreign Commonwealth and Development Office)", queryHints: ["FCDO call for proposals", "UK aid grant", "tender"] },
  { category: "BILATERAL_DONORS", name: "EU ECHO (European Civil Protection and Humanitarian Aid)", queryHints: ["ECHO funding", "humanitarian grant", "call for proposals"] },
  { category: "BILATERAL_DONORS", name: "EU INTPA (development and partnerships)", queryHints: ["INTPA call for proposals", "EuropeAid", "DG INTPA"] },
  { category: "BILATERAL_DONORS", name: "SIDA (Swedish International Development)", queryHints: ["Sida call for proposals", "grant", "CSO"] },
  { category: "BILATERAL_DONORS", name: "BMZ (German Federal Ministry for Economic Cooperation)", queryHints: ["BMZ funding", "grant", "NGO"] },
  { category: "BILATERAL_DONORS", name: "GFFO (German Federal Foreign Office humanitarian grants)", queryHints: ["GFFO grant", "humanitarian", "call for proposals"] },
  { category: "BILATERAL_DONORS", name: "GIZ partnership opportunities", queryHints: ["GIZ call for proposals", "partnership", "grant"] },
  { category: "BILATERAL_DONORS", name: "AFD (Agence Française de Développement)", queryHints: ["AFD call for proposals", "NGO", "grant"] },
  { category: "BILATERAL_DONORS", name: "DGCS (Italian Development Cooperation)", queryHints: ["AICS call for proposals", "DGCS grant", "NGO"] },
  { category: "BILATERAL_DONORS", name: "AECID (Spanish Agency for International Development)", queryHints: ["AECID convocatoria", "grant", "NGO"] },
  { category: "BILATERAL_DONORS", name: "MFA Netherlands (Dutch Relief Alliance and bilateral)", queryHints: ["Dutch Relief Alliance funding", "Netherlands MFA call for proposals"] },
  { category: "BILATERAL_DONORS", name: "DFAT (Australian Department of Foreign Affairs)", queryHints: ["DFAT grant", "aid funding", "call for proposals"] },
  { category: "BILATERAL_DONORS", name: "GAC (Global Affairs Canada)", queryHints: ["Global Affairs Canada call for proposals", "WUSC", "CSO funding"] },
  { category: "BILATERAL_DONORS", name: "KOICA (Korea International Cooperation Agency)", queryHints: ["KOICA call for proposals", "grant", "NGO"] },
  { category: "BILATERAL_DONORS", name: "JICA (Japan International Cooperation Agency)", queryHints: ["JICA grant", "partnership", "call for proposals"] },
  { category: "BILATERAL_DONORS", name: "MFA Norway (Norad grants)", queryHints: ["Norad call for proposals", "grant", "civil society"] },
  { category: "BILATERAL_DONORS", name: "MFA Denmark (Danida)", queryHints: ["Danida call for proposals", "grant", "civil society"] },
  { category: "BILATERAL_DONORS", name: "MFA Finland", queryHints: ["Finland MFA call for proposals", "grant", "civil society"] },
  { category: "BILATERAL_DONORS", name: "MFA Switzerland (SDC — Swiss Agency for Development)", queryHints: ["SDC call for proposals", "grant", "civil society"] },
  { category: "BILATERAL_DONORS", name: "MFA Luxembourg", queryHints: ["Luxembourg development cooperation call for proposals", "grant"] },
  { category: "BILATERAL_DONORS", name: "MFA Belgium", queryHints: ["Belgium development cooperation call for proposals", "grant"] },
  { category: "BILATERAL_DONORS", name: "MFA Ireland (Irish Aid)", queryHints: ["Irish Aid call for proposals", "grant", "civil society"] },
  { category: "BILATERAL_DONORS", name: "MFA New Zealand", queryHints: ["New Zealand MFAT call for proposals", "grant"] },
  { category: "BILATERAL_DONORS", name: "BPRM (U.S. Bureau of Population, Refugees, and Migration)", queryHints: ["BPRM funding opportunity", "NOFO", "PRM"] },
  { category: "BILATERAL_DONORS", name: "U.S. Department of State humanitarian grants", queryHints: ["Department of State NOFO", "humanitarian assistance"] },
  { category: "BILATERAL_DONORS", name: "U.S. Department of Labor (child labor and education grants)", queryHints: ["US Department of Labor grant", "child labor", "education"] },

  // MAJOR INTERNATIONAL NGOS WITH SUBGRANT PROGRAMS
  { category: "INGO_SUBGRANTS", name: "Save the Children (subgrants and partnerships)", queryHints: ["Save the Children subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "IRC (International Rescue Committee) subgrant windows", queryHints: ["IRC subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "World Vision partnership and subgrant opportunities", queryHints: ["World Vision subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "Mercy Corps subgrant programs", queryHints: ["Mercy Corps subgrant", "call for proposals", "partner"] },
  { category: "INGO_SUBGRANTS", name: "Oxfam partnership grants", queryHints: ["Oxfam subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "CARE International subgrants", queryHints: ["CARE subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "Catholic Relief Services (CRS) subgrants", queryHints: ["CRS subaward", "subgrant", "partner"] },
  { category: "INGO_SUBGRANTS", name: "Plan International subgrants", queryHints: ["Plan International subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "Action Against Hunger (ACF) partnership funds", queryHints: ["Action Against Hunger subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "Medecins Sans Frontieres (MSF) — limited partnerships", queryHints: ["MSF partnership", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "IMC (International Medical Corps) subgrants", queryHints: ["International Medical Corps subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "Relief International subgrants", queryHints: ["Relief International subgrant", "partner"] },
  { category: "INGO_SUBGRANTS", name: "NRC (Norwegian Refugee Council) subgrants", queryHints: ["NRC subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "DRC (Danish Refugee Council) subgrant windows", queryHints: ["Danish Refugee Council subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "Terre des Hommes grants and partnerships", queryHints: ["Terre des Hommes partnership", "subgrant", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "War Child partnership funds", queryHints: ["War Child subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "ChildFund International subgrants", queryHints: ["ChildFund subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "SOS Children's Villages partnerships", queryHints: ["SOS Children's Villages partnership", "subgrant"] },
  { category: "INGO_SUBGRANTS", name: "Handicap International / Humanity & Inclusion grants", queryHints: ["Humanity & Inclusion subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "Première Urgence Internationale subgrants", queryHints: ["Première Urgence Internationale subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "ACTED subgrant opportunities", queryHints: ["ACTED subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "Solidarités International subgrants", queryHints: ["Solidarites International subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "INTERSOS subgrant windows", queryHints: ["INTERSOS subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "Caritas Internationalis grants", queryHints: ["Caritas subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "Samaritan's Purse partnership funds", queryHints: ["Samaritan's Purse subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "Church World Service (CWS) grants", queryHints: ["Church World Service subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "Lutheran World Federation (LWF) grants", queryHints: ["Lutheran World Federation subgrant", "partner", "call for proposals"] },
  { category: "INGO_SUBGRANTS", name: "World Relief subgrants", queryHints: ["World Relief subgrant", "partner", "call for proposals"] },

  // MAJOR PRIVATE FOUNDATIONS
  { category: "PRIVATE_FOUNDATIONS", name: "Bill & Melinda Gates Foundation (Grand Challenges and global health)", queryHints: ["Gates Foundation Grand Challenges", "request for proposals", "grant"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Wellcome Trust (health and humanitarian)", queryHints: ["Wellcome funding", "call", "grant"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Children's Investment Fund Foundation (CIFF)", queryHints: ["CIFF grant", "call for proposals"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Elton John AIDS Foundation", queryHints: ["Elton John AIDS Foundation grant", "request for proposals"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Conrad N. Hilton Foundation (humanitarian and child welfare)", queryHints: ["Hilton Foundation grant", "call for proposals"] },
  { category: "PRIVATE_FOUNDATIONS", name: "IKEA Foundation (refugee and displacement)", queryHints: ["IKEA Foundation grant", "refugee", "call for proposals"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Novo Nordisk Foundation", queryHints: ["Novo Nordisk Foundation grant", "call for proposals"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Robert Wood Johnson Foundation", queryHints: ["RWJF call for proposals", "grant"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Bloomberg Philanthropies (global health and humanitarian)", queryHints: ["Bloomberg Philanthropies grant", "call for proposals"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Skoll Foundation (social entrepreneurship)", queryHints: ["Skoll Award", "grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Omidyar Network", queryHints: ["Omidyar funding", "grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Open Society Foundations (OSF)", queryHints: ["Open Society Foundations grant", "call for proposals"] },
  { category: "PRIVATE_FOUNDATIONS", name: "MacArthur Foundation", queryHints: ["MacArthur Foundation grant", "call for proposals"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Ford Foundation", queryHints: ["Ford Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Rockefeller Foundation", queryHints: ["Rockefeller Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Hewlett Foundation", queryHints: ["Hewlett Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Packard Foundation", queryHints: ["Packard Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "JPMorgan Chase Foundation", queryHints: ["JPMorgan Chase Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Bank of America Foundation", queryHints: ["Bank of America Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Mastercard Foundation", queryHints: ["Mastercard Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Google.org (humanitarian and education grants)", queryHints: ["Google.org grant", "call for proposals"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Microsoft AI for Humanitarian Action", queryHints: ["AI for Humanitarian Action", "grant", "call for proposals"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Cisco Foundation", queryHints: ["Cisco Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Salesforce.org", queryHints: ["Salesforce.org grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "LEGO Foundation (children and play-based learning)", queryHints: ["LEGO Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Oak Foundation (child protection and MHPSS)", queryHints: ["Oak Foundation grant", "call", "child protection", "MHPSS"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Porticus Foundation (child welfare)", queryHints: ["Porticus grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Sigrid Rausing Trust", queryHints: ["Sigrid Rausing Trust grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Aga Khan Foundation", queryHints: ["Aga Khan Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "King Khalid Foundation", queryHints: ["King Khalid Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Qatar Charity and Qatar Fund for Development", queryHints: ["Qatar Fund for Development grant", "Qatar Charity grant"] },
  { category: "PRIVATE_FOUNDATIONS", name: "King Salman Humanitarian Aid and Relief Centre (KSRelief)", queryHints: ["KSRelief funding", "call for proposals", "grant"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Dubai Cares (education in emergencies)", queryHints: ["Dubai Cares grant", "education in emergencies"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Mohammed bin Rashid Al Maktoum Global Initiatives", queryHints: ["MBRGI grant", "call for proposals"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Islamic Development Bank (IsDB) humanitarian grants", queryHints: ["IsDB grant", "call for proposals"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Zakat Foundation grants", queryHints: ["Zakat Foundation grant", "call for proposals"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Drosos Foundation (Middle East and youth)", queryHints: ["Drosos Foundation grant", "Middle East", "youth"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Stichting DOEN Foundation", queryHints: ["DOEN Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Bernard van Leer Foundation (early childhood)", queryHints: ["Bernard van Leer Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Robert Bosch Foundation", queryHints: ["Robert Bosch Stiftung grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Volkswagen Foundation", queryHints: ["VolkswagenStiftung grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Jacobs Foundation (children and youth)", queryHints: ["Jacobs Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Stavros Niarchos Foundation", queryHints: ["Stavros Niarchos Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Bodossaki Foundation", queryHints: ["Bodossaki Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Gulbenkian Foundation", queryHints: ["Gulbenkian Foundation grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Wellspring Philanthropic Fund", queryHints: ["Wellspring Philanthropic Fund grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Luminos Fund (education)", queryHints: ["Luminos Fund grant", "call"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Education Cannot Wait (ECW) — multi-window and acceleration grants", queryHints: ["Education Cannot Wait call for proposals", "ECW", "acceleration"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Global Partnership for Education (GPE)", queryHints: ["GPE grant", "call for proposals"] },
  { category: "PRIVATE_FOUNDATIONS", name: "Educate a Child (EAC)", queryHints: ["Educate A Child grant", "call for proposals"] },

  // DEVELOPMENT BANKS & MULTILATERAL FUNDS
  { category: "DEVELOPMENT_BANKS_MULTILATERAL", name: "World Bank — grants and trust funds open to NGOs", queryHints: ["World Bank trust fund call for proposals", "grant", "NGO"] },
  { category: "DEVELOPMENT_BANKS_MULTILATERAL", name: "Asian Development Bank (ADB) partnership grants", queryHints: ["ADB partnership grant", "CSO", "call for proposals"] },
  { category: "DEVELOPMENT_BANKS_MULTILATERAL", name: "African Development Bank (AfDB) civil society grants", queryHints: ["AfDB civil society grant", "call for proposals"] },
  { category: "DEVELOPMENT_BANKS_MULTILATERAL", name: "European Bank for Reconstruction and Development (EBRD) civil society", queryHints: ["EBRD civil society grant", "call"] },
  { category: "DEVELOPMENT_BANKS_MULTILATERAL", name: "Islamic Development Bank (IsDB)", queryHints: ["IsDB grant", "call for proposals"] },
  { category: "DEVELOPMENT_BANKS_MULTILATERAL", name: "International Finance Corporation (IFC) social grants", queryHints: ["IFC social grant", "call for proposals"] },
  { category: "DEVELOPMENT_BANKS_MULTILATERAL", name: "Global Fund (health systems and emergency)", queryHints: ["Global Fund call for proposals", "grant", "health systems"] },
  { category: "DEVELOPMENT_BANKS_MULTILATERAL", name: "Gavi (vaccine and health system grants)", queryHints: ["Gavi funding opportunity", "grant"] },
  { category: "DEVELOPMENT_BANKS_MULTILATERAL", name: "Green Climate Fund — adaptation and resilience", queryHints: ["Green Climate Fund call for proposals", "adaptation grant"] },
  { category: "DEVELOPMENT_BANKS_MULTILATERAL", name: "Global Environment Facility (GEF)", queryHints: ["GEF grant", "call for proposals"] },

  // GRANT AGGREGATORS & DATABASES TO SCRAPE DAILY
  { category: "AGGREGATORS_DATABASES", name: "ReliefWeb Opportunities (jobs and grants section)", queryHints: ["ReliefWeb opportunities grants"] },
  { category: "AGGREGATORS_DATABASES", name: "DEVEX funding opportunities", queryHints: ["Devex funding opportunity"] },
  { category: "AGGREGATORS_DATABASES", name: "Bond (UK INGO network grants)", queryHints: ["Bond funding opportunities", "grants"] },
  { category: "AGGREGATORS_DATABASES", name: "Candid / GuideStar (Foundation grants database)", queryHints: ["Candid grants", "GuideStar grants"] },
  { category: "AGGREGATORS_DATABASES", name: "GrantStation", queryHints: ["GrantStation funding opportunity"] },
  { category: "AGGREGATORS_DATABASES", name: "Grants.gov (all U.S. federal grants)", queryHints: ["site:grants.gov NOFO", "opportunity"] },
  { category: "AGGREGATORS_DATABASES", name: "FundingAlert", queryHints: ["FundingAlert grant"] },
  { category: "AGGREGATORS_DATABASES", name: "NGO Source", queryHints: ["NGOsource grant", "funding opportunity"] },
  { category: "AGGREGATORS_DATABASES", name: "Humanitarian Futures Programme", queryHints: ["Humanitarian Futures Programme funding", "grant"] },
  { category: "AGGREGATORS_DATABASES", name: "PHAP (Professionals in Humanitarian Assistance and Protection)", queryHints: ["PHAP funding", "opportunity", "grant"] },
  { category: "AGGREGATORS_DATABASES", name: "Interaction (U.S. INGO network funding alerts)", queryHints: ["InterAction funding alerts", "grant"] },
  { category: "AGGREGATORS_DATABASES", name: "OCHA Financial Tracking System", queryHints: ["OCHA FTS call for proposals", "funding"] },
  { category: "AGGREGATORS_DATABASES", name: "Development Gateway", queryHints: ["Development Gateway funding opportunity", "grant"] },
  { category: "AGGREGATORS_DATABASES", name: "GlobalGiving grants for partners", queryHints: ["GlobalGiving open call", "partner grant"] },
  { category: "AGGREGATORS_DATABASES", name: "Idealist grants section", queryHints: ["Idealist grants"] }
];

export const INARA_GEOS = ["Syria", "Afghanistan", "Lebanon", "Ukraine", "Egypt", "Turkey", "Palestine", "Gaza"];

export const INARA_SECTORS = [
  "child protection",
  "medical",
  "rehabilitation",
  "rehab",
  "MHPSS",
  "mental health",
  "psychosocial",
  "education",
  "education in emergencies",
  "WASH",
  "water sanitation hygiene",
  "livelihood",
  "economic empowerment",
  "emergency response",
  "food",
  "NFI",
  "non-food items"
];

